print("\n- EJERCICIO 1")
tupla = ('manzana','pera')
lista=list(tupla)
lista.append(input(f'Ingresa una nueva fruta, la canasta ahora mismo contiene: {lista}: '))
tupla=tuple(lista)
print(f'La canasta contiene {tupla}')

print("\n- EJERCICIO 2")
notas = (4.2, 3.8)
lista=list(notas)
lista.append(float(input(f'Ingresa la nota mas reciente, tus notas actuales son: {lista}: ')))
notas=tuple(lista)
print(f'Tu boletin actualizado es: {notas}')

print("\n- EJERCICIO 3")
perfil = ('Ana','Gómez')
lista=list(perfil)
lista.append(int(input(f'Bienvenida {lista}, para continuar ingrese su número de documento: ')))
perfil=tuple(lista)
print(f'Su registro ha sido completado con los datos: {perfil}')